info:
   app:
     name: Customer Information Service
server:
  port: 8080
aws:
  region: us-east-1

DYNAMO_DB_TABLE_NAME: 'customer_info'
USER_ACCESS_KEY_ACCESSKEYID:
USER_ACCESS_KEY_SECRETACCESSKEY: